version: '3'
services:
  neo4j:
    image: neo4j:4.4
    container_name: my-neo4j-container
    volumes:
      - ./data:/data/neo4j
      - ./plugins:/plugins/neo4j
      - ./import:/import/neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/1234 # user: neo4j password: 1234
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_dbms_security_procedures_unrestricted: apoc.*,algo.*
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 2G
      NEO4J_apoc_uuid_enabled: true
      NEO4J_dbms_default__listen__address: 0.0.0.0
      NEO4J_dbms_allow__upgrade: true
      NEO4J_dbms_default__database: neo4j
    restart: unless-stopped

  redis:
    image: 'bitnami/redis:latest'
    container_name: my-redis-container
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped


  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: my-mongodb-container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    #    volumes:
    #      - type: bind
    #        source: ./data/mongo
    #        target: /data/mongo/db
    #      - ./mongo-scripts/initdb:/docker-entrypoint-initdb.d/

    restart: unless-stopped

  acmeuser:
    image: acme-user:latest
    container_name: acme-user-container
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=admin
      - SPRING_DATA_MONGODB_USERNAME=user
      - SPRING_DATA_MONGODB_PASSWORD=pass
    depends_on:
      - mongodb
    restart: unless-stopped
